matrix:
  include:
    - language: python
      python: 3.6
      os: linux
    - language: generic
      python: 3.6
      os: osx

sudo: false
cache: pip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

install:
  - travis_retry python3 -m pip install -e .[test]

script:
  - python3 -m pytest
  - sphinx-build -q -b html -b linkcheck -d docs/_build/doctrees docs docs/_build/html
